apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: carousel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: carousel/backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/carousel"
        - name: FLASK_ENV
          value: "development"
        volumeMounts:
        - mountPath: /app/uploads
          name: uploads-storage
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: uploads-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: carousel
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: carousel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi